//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppliedJob
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int Phone_Number { get; set; }
        public byte[] Resume { get; set; }
        public string UserId { get; set; }
        public string CondidaId { get; set; }
        public int JobId { get; set; }
        public string ContentType { get; set; }
        public string FileName { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
