//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoBoard.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JoBoard_DBEntities1 : DbContext
    {
        public JoBoard_DBEntities1()
            : base("name=JoBoard_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<PostedJob> PostedJobs { get; set; }
        public virtual DbSet<SavedJob> SavedJobs { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<tblFile> tblFiles { get; set; }
        public virtual DbSet<AppliedJob> AppliedJobs { get; set; }
    }
}
