//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.PostedJobs = new HashSet<PostedJob>();
            this.SavedJobs = new HashSet<SavedJob>();
            this.AppliedJobs = new HashSet<AppliedJob>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Job_Title { get; set; }
        public string StateId { get; set; }
        public int CityId { get; set; }
        public string Job_Type { get; set; }
        public string Job_Description { get; set; }
        public string Job_Requirements { get; set; }
        public string Company_Name { get; set; }
        public string Company_Description { get; set; }
        public string Company_Website { get; set; }
        public string Company_LinkedIn { get; set; }
        public string Company_Logo { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Gender { get; set; }
    
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostedJob> PostedJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedJob> SavedJobs { get; set; }
        public virtual state state { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppliedJob> AppliedJobs { get; set; }
    }
}
